modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="chilean_craft"
version="1.7.6"
displayName="Chilean Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Srperrito, salvador fonseca, sesba, mcreator"

[[dependencies.chilean_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




