/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.chilecraft;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.mcreator.chilecraft.gui.GuiVillagerAldeanoMotemeiTraderGui2;
import net.mcreator.chilecraft.gui.GuiTorno;
import net.mcreator.chilecraft.gui.GuiTioaceitregui2;
import net.mcreator.chilecraft.gui.GuiTioaceitegui;
import net.mcreator.chilecraft.gui.GuiTinajaIN;
import net.mcreator.chilecraft.gui.GuiTianajgrnde;
import net.mcreator.chilecraft.gui.GuiPipek;
import net.mcreator.chilecraft.gui.GuiParrillagui;
import net.mcreator.chilecraft.gui.GuiPappi;
import net.mcreator.chilecraft.gui.GuiOlaa;
import net.mcreator.chilecraft.gui.GuiMonedero;
import net.mcreator.chilecraft.gui.GuiHuaso2;
import net.mcreator.chilecraft.gui.GuiDealerguui;
import net.mcreator.chilecraft.gui.GuiCHANCHO;
import net.mcreator.chilecraft.gui.GuiAldeanoMotemeiGui1;
import net.mcreator.chilecraft.gui.GuiAldeanoHuasoGui1;
import net.mcreator.chilecraft.gui.GuiAldeanoHaitianoGui2;
import net.mcreator.chilecraft.gui.GuiAldeanoHaitianoGui1;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsChileanCraftMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsChileanCraftMod() {
		sounds.put(new ResourceLocation("chilean_craft", "laconsentida"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "laconsentida")));
		sounds.put(new ResourceLocation("chilean_craft", "loyola"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "loyola")));
		sounds.put(new ResourceLocation("chilean_craft", "money"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "money")));
		sounds.put(new ResourceLocation("chilean_craft", "genral"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "genral")));
		sounds.put(new ResourceLocation("chilean_craft", "cueca"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "cueca")));
		sounds.put(new ResourceLocation("chilean_craft", "don"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "don")));
		sounds.put(new ResourceLocation("chilean_craft", "tambor"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "tambor")));
		sounds.put(new ResourceLocation("chilean_craft", "kutlrun1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "kutlrun1")));
		sounds.put(new ResourceLocation("chilean_craft", "tambor2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "tambor2")));
		sounds.put(new ResourceLocation("chilean_craft", "kultrun23"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "kultrun23")));
		sounds.put(new ResourceLocation("chilean_craft", "a"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "a")));
		sounds.put(new ResourceLocation("chilean_craft", "ku"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "ku")));
		sounds.put(new ResourceLocation("chilean_craft", "ky"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "ky")));
		sounds.put(new ResourceLocation("chilean_craft", "platillo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "platillo")));
		sounds.put(new ResourceLocation("chilean_craft", "tambo1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "tambo1")));
		sounds.put(new ResourceLocation("chilean_craft", "tambor1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "tambor1")));
		sounds.put(new ResourceLocation("chilean_craft", "kl1"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "kl1")));
		sounds.put(new ResourceLocation("chilean_craft", "tma2"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "tma2")));
		sounds.put(new ResourceLocation("chilean_craft", "pla"), new net.minecraft.util.SoundEvent(new ResourceLocation("chilean_craft", "pla")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsChileanCraftMod.ModElement.class)
					elements.add((ElementsChileanCraftMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsChileanCraftMod.ModElement::initElements);
		this.addNetworkMessage(ChileanCraftModVariables.WorldSavedDataSyncMessageHandler.class,
				ChileanCraftModVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = ChileanCraftModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = ChileanCraftModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				ChileanCraftMod.PACKET_HANDLER.sendTo(new ChileanCraftModVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				ChileanCraftMod.PACKET_HANDLER.sendTo(new ChileanCraftModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = ChileanCraftModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				ChileanCraftMod.PACKET_HANDLER.sendTo(new ChileanCraftModVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			ChileanCraftMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiTorno.GUIID)
				return new GuiTorno.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTinajaIN.GUIID)
				return new GuiTinajaIN.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTianajgrnde.GUIID)
				return new GuiTianajgrnde.GuiContainerMod(world, x, y, z, player);
			if (id == GuiCHANCHO.GUIID)
				return new GuiCHANCHO.GuiContainerMod(world, x, y, z, player);
			if (id == GuiPipek.GUIID)
				return new GuiPipek.GuiContainerMod(world, x, y, z, player);
			if (id == GuiOlaa.GUIID)
				return new GuiOlaa.GuiContainerMod(world, x, y, z, player);
			if (id == GuiVillagerAldeanoMotemeiTraderGui2.GUIID)
				return new GuiVillagerAldeanoMotemeiTraderGui2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAldeanoMotemeiGui1.GUIID)
				return new GuiAldeanoMotemeiGui1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAldeanoHaitianoGui1.GUIID)
				return new GuiAldeanoHaitianoGui1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAldeanoHaitianoGui2.GUIID)
				return new GuiAldeanoHaitianoGui2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAldeanoHuasoGui1.GUIID)
				return new GuiAldeanoHuasoGui1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiParrillagui.GUIID)
				return new GuiParrillagui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiHuaso2.GUIID)
				return new GuiHuaso2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTioaceitegui.GUIID)
				return new GuiTioaceitegui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTioaceitregui2.GUIID)
				return new GuiTioaceitregui2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDealerguui.GUIID)
				return new GuiDealerguui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiPappi.GUIID)
				return new GuiPappi.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMonedero.GUIID)
				return new GuiMonedero.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiTorno.GUIID)
				return new GuiTorno.GuiWindow(world, x, y, z, player);
			if (id == GuiTinajaIN.GUIID)
				return new GuiTinajaIN.GuiWindow(world, x, y, z, player);
			if (id == GuiTianajgrnde.GUIID)
				return new GuiTianajgrnde.GuiWindow(world, x, y, z, player);
			if (id == GuiCHANCHO.GUIID)
				return new GuiCHANCHO.GuiWindow(world, x, y, z, player);
			if (id == GuiPipek.GUIID)
				return new GuiPipek.GuiWindow(world, x, y, z, player);
			if (id == GuiOlaa.GUIID)
				return new GuiOlaa.GuiWindow(world, x, y, z, player);
			if (id == GuiVillagerAldeanoMotemeiTraderGui2.GUIID)
				return new GuiVillagerAldeanoMotemeiTraderGui2.GuiWindow(world, x, y, z, player);
			if (id == GuiAldeanoMotemeiGui1.GUIID)
				return new GuiAldeanoMotemeiGui1.GuiWindow(world, x, y, z, player);
			if (id == GuiAldeanoHaitianoGui1.GUIID)
				return new GuiAldeanoHaitianoGui1.GuiWindow(world, x, y, z, player);
			if (id == GuiAldeanoHaitianoGui2.GUIID)
				return new GuiAldeanoHaitianoGui2.GuiWindow(world, x, y, z, player);
			if (id == GuiAldeanoHuasoGui1.GUIID)
				return new GuiAldeanoHuasoGui1.GuiWindow(world, x, y, z, player);
			if (id == GuiParrillagui.GUIID)
				return new GuiParrillagui.GuiWindow(world, x, y, z, player);
			if (id == GuiHuaso2.GUIID)
				return new GuiHuaso2.GuiWindow(world, x, y, z, player);
			if (id == GuiTioaceitegui.GUIID)
				return new GuiTioaceitegui.GuiWindow(world, x, y, z, player);
			if (id == GuiTioaceitregui2.GUIID)
				return new GuiTioaceitregui2.GuiWindow(world, x, y, z, player);
			if (id == GuiDealerguui.GUIID)
				return new GuiDealerguui.GuiWindow(world, x, y, z, player);
			if (id == GuiPappi.GUIID)
				return new GuiPappi.GuiWindow(world, x, y, z, player);
			if (id == GuiMonedero.GUIID)
				return new GuiMonedero.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsChileanCraftMod elements;
		protected final int sortid;
		public ModElement(ElementsChileanCraftMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
